config/routes.rb
Rails.application.routes.draw do
  namespace :api, as: nil, defaults: { format: 'json' } do
    namespace :v1, as: nil do
      namespace :users do
        post 'authenticate',  to: 'sessions#create', as: 'login'
      end
      resources :transactions , only: %i() do
        collection do
          post :authorize
        end
        member do
          post :refund
        end
      end
    end
  end

  resources :transactions
  resources :merchants

  root to: 'transactions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/merchant.rb
class Merchant < User

  before_destroy do
    cannot_delete_with_transactions
    throw(:abort) if errors.present?
  end

  def cannot_delete_with_transactions
    errors.add(:base, 'Cannot delete Merchant with transactions') if transactions.any?
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /merchants/1/edit
  def edit
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def merchant_params
      parameter = params.require(:merchant).permit(:name, :email, :status, :amount, :total_transaction_sum, :password_confirmation, :password)
      if ((params['action'] == "update") && (params.dig(:merchant, :with_password) == '0'))
        parameter.except(:password, :password_confirmation)
      else
        parameter
      end
    end
end

app/helpers/api/v1/merchants_helper.rb
module Api::V1::MerchantsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_with(model: merchant, local: true) do |form| %>
  <% if merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
        <% merchant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :update_with_password %>
    <%= form.check_box :with_password%>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(["inactive", "active"], form.object.status), {:include_blank => "Select status"}, { class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :total_transaction_sum %>
    <%= form.text_field :total_transaction_sum, class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<h1>Merchants</h1>

<%= link_to 'New Merchant', new_merchant_path, class: 'btn btn-info' %>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Type</th>
      <th>Status</th>
      <th>Amount</th>
      <th>Total transaction sum</th>
      <th>Created at</th>
      <th colspan="3"> Action </th>
    </tr>
  </thead>

  <tbody>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.name %></td>
        <td><%= merchant.email %></td>
        <td><%= merchant.type %></td>
        <td><%= merchant.status %></td>
        <td><%= merchant.amount %></td>
        <td><%= merchant.total_transaction_sum %></td>
        <td><%= display_date merchant.created_at %></td>
        <td><%= link_to 'Show', merchant %></td>
        <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
        <td><%= link_to 'Destroy', merchant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/merchants/new.html.erb
<h1>New Merchant</h1>

<%= render 'form', merchant: @merchant %>

<%= link_to 'Back', merchants_path %>

app/views/merchants/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @merchant.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @merchant.email %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @merchant.type %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @merchant.status %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @merchant.amount %>
  </p>

  <p>
    <strong>Total transaction sum:</strong>
    <%= @merchant.total_transaction_sum %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= display_date @merchant.created_at %>
  </p>
</div>

<%= link_to 'Edit', edit_merchant_path(@merchant), class: 'btn btn-info' %> |
<%= link_to 'Back', merchants_path, class: 'btn btn-info' %>