config/routes.rb
Rails.application.routes.draw do
  namespace :api, as: nil, defaults: { format: 'json' } do
    namespace :v1, as: nil do
      namespace :users do
        post 'authenticate',  to: 'sessions#create', as: 'login'
      end
      resources :transactions , only: %i() do
        collection do
          post :authorize
        end
        member do
          post :refund
        end
      end
    end
  end

  resources :transactions
  resources :merchants

  root to: 'transactions#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/transactions_controller.rb
module Api
  module V1
    class TransactionsController < Api::V1::ApiController
      before_action :authenticate_request
      before_action :user_active?
      before_action :set_transaction, only: [:refund]

      def authorize
        transaction = TransactionService.call(transaction_params: transaction_params, current_user: current_user)
        if transaction.success?
          render_success_response({}, I18n.t('created', resource: 'Transaction'))
        else
          render_unprocessable_entity(transaction.errors)
        end
      end

      def refund
        transaction = RefundTransactionService.call(transaction: @transaction, current_user: current_user)
        if transaction.success?
          render_success_response({}, I18n.t('created', resource: 'Transaction'))
        else
          render_unprocessable_entity(transaction.errors)
        end
      end

      private

      def set_transaction
        @transaction = current_user.transactions.find(params[:id])
      end

      def user_active?
        render_unauthorized_response({inactive: I18n.t('errors.inactive_account')}) and return unless current_user.active?
      end

      def transaction_params
        params.require(:transaction).permit(:amount, :customer_email, :customer_phone)
      end
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
end

app/helpers/api/v1/transactions_helper.rb
module Api::V1::TransactionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Amount</th>
      <th>User</th>
      <th>Parent</th>
      <th>Customer email</th>
      <th>Customer phone</th>
      <th>Status</th>
      <th> Action</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.amount %></td>
        <td><%= transaction.user_id %></td>
        <td><%= transaction.parent_id %></td>
        <td><%= transaction.customer_email %></td>
        <td><%= transaction.customer_phone %></td>
        <td><%= transaction.status %></td>
        <td><%= link_to 'Show', transaction_path(transaction) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/transactions/show.html.erb
<div class="container">
  <p>
    <strong>Amount:</strong>
    <%= @transaction.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @transaction.user_id %>
  </p>

  <% if @transaction.parent_id %>
    <p>
      <strong>Parent:</strong>
       <%= link_to @transaction.parent_id, transaction_path(@transaction.parent_id) %>
    </p>
  <% end %>

  <p>
    <strong>Customer email:</strong>
    <%= @transaction.customer_email %>
  </p>

  <p>
    <strong>Customer phone:</strong>
    <%= @transaction.customer_phone %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @transaction.status %>
  </p>
</div>

<%= link_to 'Back', transactions_path, class: 'btn btn-info' %>